name: Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure with Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CLIENT_ID }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    - name: Install Azure CLI
      run: |
           # Install Azure CLI
           curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Build and deploy to Azure Web App
      run: |
        # Build your app here (if needed)

        # Deploy to Azure Web App
        az webapp deployment source config-zip \
          -g RG_IAC \
          -n Samplehelloworldapp \
          --src ./
