name: Azure Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: list the files
      run: |
           pwd
           chmod -R 777 ./*
           ls -la
    
    - name: Install Azure CLI
      run: |
           # Install Azure CLI
           curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Log in to Azure with Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # - name: Build and deploy to Azure Web App
    #   run: |
    #     # Create a zip file containing the index.html
    #     #zip -r code.zip index.html

    #     # Deploy to Azure Web App
    #     az webapp deployment source ./index.html \
    #       -g RG_IAC \
    #       -n Samplehelloworldapp \

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: /home/runner/work/hellow-world/hellow-world/index.html # Update this path to the folder containing your HTML file
          credentials: ${{ secrets.AZURE_CREDENTIALS }}

        
    
    # - name: Build and deploy to Azure Web App
    #   run: |
    #     # Create a zip file containing the index.html
    #     zip -r code.zip index.html

    #     # Deploy to Azure Web App
    #     az webapp deployment source config-zip \
    #       -g RG_IAC \
    #       -n Samplehelloworldapp \
    #       --src ./code.zip
    
